stages:
  - install
  - default-migration
  - migrate-magazine
  - migrate-books

variables:
  NODE_ENV: "production"

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - echo "Installing dependencies..."
    - npm install


install_dependencies:
  stage: default-migration
  script:
    - echo "Installing dependencies..."
    - npm run import


install_dependencies:
  stage: migrate-magazine
  script:
    - echo "Magazine migration..."
    - npm run magazine-migration

install_dependencies:
  stage: migrate-books
  script:
    - echo "Book migration..."
    - npm run book-migration

